### ISSUE TITLE
Invalid behavior of amsads binding with Beckhoff BX9000

### ISSUE THREAD

**Issue by splatch** [ConnectorIO/connectorio-addons#52]
Reported here:
https://community.openhab.org/t/co7io-industrial-integrations-with-beckhoff-ads-siemens-s7/89021/82

The BX9000 does not support symbolic addresses, hence it should not be scanned for these.

```
09:45:29.812 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'co7io-amsads:network:192_168_7_10_1_1:192_168_7_21' changed from INITIALIZING to UNKNOWN
09:45:30.635 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'co7io-amsads:network:192_168_7_10_1_1:192_168_7_21' changed from UNKNOWN to OFFLINE (HANDLER_INITIALIZING_ERROR): Could not retrieve data type and symbol information from ADS device org.apache.plc4x.java.api.exceptions.PlcException: Result is null
09:45:47.010 [ERROR] [.connection.DefaultNettyPlcConnection] - unknown error, close the connection
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[?:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by splatch** [comment]
Completed with 7ac27a1.
